/**
 * Handler Configs
 */
// tslint:disable:max-func-body-length

import fs from 'fs';
import pth from 'path';
import express from 'express';
import globby from 'globby';
import { genPathResolve } from '@huiji/shared-utils';
import { languageInfos } from '@rimtrans/core';
import io from '@rimtrans/io';
import { ServerListenerFactory } from '../utils-server';
import { Configs, newConfigs } from './model';

const CONFIGS_JSON = 'configs.json';

const factory: ServerListenerFactory<'configs' | 'configsInit'> = (
  internal,
  external,
) => {
  const configsPath = genPathResolve(external)(CONFIGS_JSON);

  const save = async (c: Configs) => {
    try {
      await io.save(
        configsPath,
        `/* !!DANGER!! DO NOT edit this file! */\n${JSON.stringify(c)}`,
      );
    } catch (error) {
      // TODO
    }
  };
  const load = async (): Promise<Configs> => {
    try {
      const content = await io.load(configsPath);

      return JSON.parse(content) as Configs;
    } catch (error) {
      return newConfigs();
    }
  };

  return async (ws, data) => {
    if (data) {
      await save(data);
    } else {
      if (await io.exists(configsPath)) {
        const c = await load();
        ws.send('configs', c);
      } else {
        const c = newConfigs();
        await save(c);
        ws.send('configs', c);
      }
    }
  };
};

export const configs: ServerListenerFactory<'configs'> = factory;
export const configsInit: ServerListenerFactory<'configsInit'> = factory;
