using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RimTrans.Builder.Xml
{
    static class DefTypeNameOf
    {
        static readonly string Unknown = "Unknown";
        static readonly string Def = "Def";
        static readonly string BiomeDef = "BiomeDef";
        static readonly string BodyDef = "BodyDef";
        static readonly string BodyPartDef = "BodyPartDef";
        static readonly string BodyPartGroupDef = "BodyPartGroupDef";
        static readonly string BuildableDef = "BuildableDef";
        static readonly string ChemicalDef = "ChemicalDef";
        static readonly string ConceptDef = "ConceptDef";
        static readonly string DamageDef = "DamageDef";
        static readonly string DesignationCategoryDef = "DesignationCategoryDef";
        static readonly string DesignationDef = "DesignationDef";
        static readonly string DifficultyDef = "DifficultyDef";
        static readonly string DutyDef = "DutyDef";
        static readonly string EffecterDef = "EffecterDef";
        static readonly string FactionDef = "FactionDef";
        static readonly string GenStepDef = "GenStepDef";
        static readonly string HairDef = "HairDef";
        static readonly string HediffDef = "HediffDef";
        static readonly string HediffGiverSetDef = "HediffGiverSetDef";
        static readonly string HistoryAutoRecorderDef = "HistoryAutoRecorderDef";
        static readonly string HistoryAutoRecorderGroupDef = "HistoryAutoRecorderGroupDef";
        static readonly string IncidentDef = "IncidentDef";
        static readonly string InstructionDef = "InstructionDef";
        static readonly string InteractionDef = "InteractionDef";
        static readonly string JobDef = "JobDef";
        static readonly string JoyGiverDef = "JoyGiverDef";
        static readonly string JoyKindDef = "JoyKindDef";
        static readonly string KeyBindingCategoryDef = "KeyBindingCategoryDef";
        static readonly string KeyBindingDef = "KeyBindingDef";
        static readonly string LifeStageDef = "LifeStageDef";
        static readonly string MainTabDef = "MainTabDef";
        static readonly string MapConditionDef = "MapConditionDef";
        static readonly string MapGeneratorDef = "MapGeneratorDef";
        static readonly string MentalBreakDef = "MentalBreakDef";
        static readonly string MentalStateDef = "MentalStateDef";
        static readonly string NeedDef = "NeedDef";
        static readonly string PawnCapacityDef = "PawnCapacityDef";
        static readonly string PawnGroupKindDef = "PawnGroupKindDef";
        static readonly string PawnKindDef = "PawnKindDef";
        static readonly string PawnRelationDef = "PawnRelationDef";
        static readonly string RaidStrategyDef = "RaidStrategyDef";
        static readonly string RecipeDef = "RecipeDef";
        static readonly string RecordDef = "RecordDef";
        static readonly string ResearchProjectDef = "ResearchProjectDef";
        static readonly string RoofDef = "RoofDef";
        static readonly string RoomRoleDef = "RoomRoleDef";
        static readonly string RoomStatDef = "RoomStatDef";
        static readonly string RuleDef = "RuleDef";
        static readonly string RulePackDef = "RulePackDef";
        static readonly string ScatterableDef = "ScatterableDef";
        static readonly string ScenarioDef = "ScenarioDef";
        static readonly string ScenPartDef = "ScenPartDef";
        static readonly string SkillDef = "SkillDef";
        static readonly string SongDef = "SongDef";
        static readonly string SoundDef = "SoundDef";
        static readonly string SpecialThingFilterDef = "SpecialThingFilterDef";
        static readonly string StatCategoryDef = "StatCategoryDef";
        static readonly string StatDef = "StatDef";
        static readonly string StorytellerDef = "StorytellerDef";
        static readonly string StuffCategoryDef = "StuffCategoryDef";
        static readonly string TaleDef = "TaleDef";
        static readonly string TerrainDef = "TerrainDef";
        static readonly string ThingCategoryDef = "ThingCategoryDef";
        static readonly string ThingDef = "ThingDef";
        static readonly string ThinkTreeDef = "ThinkTreeDef";
        static readonly string ThoughtDef = "ThoughtDef";
        static readonly string TimeAssignmentDef = "TimeAssignmentDef";
        static readonly string TraderKindDef = "TraderKindDef";
        static readonly string TrainableDef = "TrainableDef";
        static readonly string TraitDef = "TraitDef";
        static readonly string TransferableSorterDef = "TransferableSorterDef";
        static readonly string WeatherDef = "WeatherDef";
        static readonly string WorkGiverDef = "WorkGiverDef";
        static readonly string WorkTypeDef = "WorkTypeDef";
        static readonly string WorldObjectDef = "WorldObjectDef";
    }
}
