using System;

namespace RimTrans.Xml
{
    public enum DefType : int
    {
        // Default/Unknown
        Unknown,

        // Base
        Def,

        // RimWorld
        BiomeDef,
        ChemicalDef,
        ConceptDef,
        DifficultyDef,
        FactionDef,
        HairDef,
        HediffGiverSetDef,
        HistoryAutoRecorderDef,
        HistoryAutoRecorderGroupDef,
        IncidentDef,
        InstructionDef,
        InteractionDef,
        JoyGiverDef,
        JoyKindDef,
        LifeStageDef,
        MainTabDef,
        NeedDef,
        PawnRelationDef,
        RaidStrategyDef,
        RecordDef,
        ScenarioDef,
        ScenPartDef,
        SkillDef,
        StatCategoryDef,
        StatDef,
        StorytellerDef,
        StuffCategoryDef,
        TaleDef,
        ThoughtDef,
        TimeAssignmentDef,
        TradeDialogSorterDef,
        TraderKindDef,
        TrainableDef,
        TraitDef,
        WorkGiverDef,

        // Verse
        BodyDef,
        BodyPartDef,
        BodyPartGroupDef,
        BuildableDef,
        DamageDef,
        DesignationCategoryDef,
        DesignationDef,
        EffecterDef,
        GenStepDef,
        HediffDef,
        JobDef,
        KeyBindingCategoryDef,
        KeyBindingDef,
        MapConditionDef,
        MapGeneratorDef,
        MentalBreakDef,
        MentalStateDef,
        PawnCapacityDef,
        PawnKindDef,
        RecipeDef,
        ResearchProjectDef,
        RoofDef,
        RoomRoleDef,
        RoomStatDef,
        RulePackDef,
        ScatterableDef,
        SongDef,
        SoundDef,
        SpecialThingFilterDef,
        TerrainDef,
        ThingCategoryDef,
        ThingDef,
        ThinkTreeDef,
        WeatherDef,
        WorkTypeDef,
        DutyDef,
    }
}
