using System;

namespace RimTransLib
{
    public enum RWDefType : int
    {
        Unknown,// Default-Unknown
        Def,// Base

        BiomeDef,
        BodyDef,
        BodyPartDef,
        BodyPartGroupDef,
        BuildableDef,
        ChemicalDef,
        ConceptDef,
        DamageDef,
        DesignationCategoryDef,
        DesignationDef,
        DifficultyDef,
        DutyDef,
        EffecterDef,
        FactionDef,
        GenStepDef,
        HairDef,
        HediffDef,
        HediffGiverSetDef,
        HistoryAutoRecorderDef,
        HistoryAutoRecorderGroupDef,
        IncidentDef,
        InstructionDef,
        InteractionDef,
        JobDef,
        JoyGiverDef,
        JoyKindDef,
        KeyBindingCategoryDef,
        KeyBindingDef,
        LifeStageDef,
        MainTabDef,
        MapConditionDef,
        MapGeneratorDef,
        MentalBreakDef,
        MentalStateDef,
        NeedDef,
        PawnCapacityDef,
        PawnGroupKindDef,
        PawnKindDef,
        PawnRelationDef,
        RaidStrategyDef,
        RecipeDef,
        RecordDef,
        ResearchProjectDef,
        RoofDef,
        RoomRoleDef,
        RoomStatDef,
        RuleDef, // new def type of A16
        RulePackDef,
        ScatterableDef,
        ScenarioDef,
        ScenPartDef,
        SkillDef,
        SongDef,
        SoundDef,
        SpecialThingFilterDef,
        StatCategoryDef,
        StatDef,
        StorytellerDef,
        StuffCategoryDef,
        TaleDef,
        TerrainDef,
        ThingCategoryDef,
        ThingDef,
        ThinkTreeDef,
        ThoughtDef,
        TimeAssignmentDef,
        TraderKindDef,
        TrainableDef,
        TraitDef,
        TransferableSorterDef, // new def type of A16
        WeatherDef,
        WorkGiverDef,
        WorkTypeDef,
        WorldObjectDef,
    }
}
