/* eslint-disable @typescript-eslint/no-explicit-any */
import * as languages from '../src/languages';

export function genProgress(): string {
  const record: Record<string, number> = {
    English: 1,
  };

  const count = (dict: any): number => {
    let current = 0;
    Object.values(dict).forEach(v => {
      if (v) {
        if (typeof v === 'string') {
          current += 1;
          return;
        }
        current += count(v);
      }
    });

    return current;
  };

  const totalEnglish = count(languages.English.dict);

  Object.entries(languages).forEach(([name, { dict }]) => {
    if (name === 'English') {
      return;
    }
    const total = count(dict);
    record[name] = total / totalEnglish;
  });

  const rows = Object.entries(record).map(
    ([name, progress]) => `export const ${name} = ${progress};`,
  );

  return `// generate by script/gen-progress.ts, do not edit this file by hand.
${rows.join('\n')}
`;
}
